apiVersion: v1
kind: Service
metadata:
  name: gitlab-web
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30011
    name: web
  - port: 22
    nodePort: 30012
    name: ssh
  - port: 443
    nodePort: 30013
    name: secure
  selector:
    app: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        env:
        - name: hostname
          value: 0.0.0.0
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 443
          name: secure
        - containerPort: 80
          name: webui
        volumeMounts:
        - name: config
          mountPath: /etc/gitlab
          subPath: config
        - name: logs
          mountPath: /var/log/gitlab
          subPath: logs
        - name: data
          mountPath: /var/opt/gitlab
          subPath: data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: gitlab-config
      - name: logs
        persistentVolumeClaim:
          claimName: gitlab-logs
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-data
