kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-config
  annotations:
    volume.beta.kubernetes.io/storage-class: "gitlab-config"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
