kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "gitlab-data"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
