kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: "gitlab-logs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
